import type { Plant } from './types';

export const PLANTS: Plant[] = [
  {
    id: 'monstera',
    name: '龟背竹',
    scientificName: 'Monstera deliciosa',
    family: '天南星科',
    genus: '龟背竹属',
    description: '龟背竹叶片巨大，呈心形，成熟叶片有独特的裂口和孔洞，是著名的室内观叶植物。',
    lightRequirement: 'medium',
    waterRequirement: 'medium',
    temperatureRange: '18-28°C',
    colorSeed: 1,
    shapeType: 'leafy'
  },
  {
    id: 'ficus-lyrata',
    name: '琴叶榕',
    scientificName: 'Ficus lyrata',
    family: '桑科',
    genus: '榕属',
    description: '琴叶榕因叶片形似提琴而得名，株型挺拔，是当下流行的大型室内绿植。',
    lightRequirement: 'strong',
    waterRequirement: 'medium',
    temperatureRange: '15-28°C',
    colorSeed: 2,
    shapeType: 'tall'
  },
  {
    id: 'tillandsia',
    name: '空气凤梨',
    scientificName: 'Tillandsia',
    family: '凤梨科',
    genus: '铁兰属',
    description: '空气凤梨无需土壤即可生长，通过叶片吸收空气中的水分和养分，造型独特。',
    lightRequirement: 'medium',
    waterRequirement: 'dry',
    temperatureRange: '15-30°C',
    colorSeed: 3,
    shapeType: 'bushy'
  },
  {
    id: 'pothos',
    name: '绿萝',
    scientificName: 'Epipremnum aureum',
    family: '天南星科',
    genus: '麒麟叶属',
    description: '绿萝是最常见的室内观叶植物，生命力顽强，可水培或土培，有净化空气的作用。',
    lightRequirement: 'weak',
    waterRequirement: 'medium',
    temperatureRange: '15-28°C',
    colorSeed: 4,
    shapeType: 'vine'
  },
  {
    id: 'succulent',
    name: '多肉植物',
    scientificName: 'Succulent',
    family: '景天科',
    genus: '景天属',
    description: '多肉植物叶片肥厚多汁，能储存大量水分，品种繁多，形态各异，极易养护。',
    lightRequirement: 'strong',
    waterRequirement: 'dry',
    temperatureRange: '10-30°C',
    colorSeed: 5,
    shapeType: 'cactus'
  },
  {
    id: 'fern',
    name: '蕨类植物',
    scientificName: 'Pteridophyta',
    family: '凤尾蕨科',
    genus: '凤尾蕨属',
    description: '蕨类植物是古老的植物类群，叶片细密如羽毛，喜欢湿润阴凉的环境。',
    lightRequirement: 'weak',
    waterRequirement: 'wet',
    temperatureRange: '18-25°C',
    colorSeed: 6,
    shapeType: 'fern'
  },
  {
    id: 'snake-plant',
    name: '虎尾兰',
    scientificName: 'Sansevieria trifasciata',
    family: '天门冬科',
    genus: '虎尾兰属',
    description: '虎尾兰叶片挺直如剑，带有美丽的斑纹，夜间释放氧气，是卧室的理想植物。',
    lightRequirement: 'medium',
    waterRequirement: 'dry',
    temperatureRange: '15-30°C',
    colorSeed: 7,
    shapeType: 'tall'
  },
  {
    id: 'peace-lily',
    name: '白掌',
    scientificName: 'Spathiphyllum',
    family: '天南星科',
    genus: '白鹤芋属',
    description: '白掌又名一帆风顺，佛焰苞洁白优雅，能有效净化室内空气中的有害物质。',
    lightRequirement: 'weak',
    waterRequirement: 'wet',
    temperatureRange: '20-28°C',
    colorSeed: 8,
    shapeType: 'leafy'
  },
  {
    id: 'rubber-plant',
    name: '橡皮树',
    scientificName: 'Ficus elastica',
    family: '桑科',
    genus: '榕属',
    description: '橡皮树叶片宽大厚实，呈深绿色有光泽，生命力强，是理想的室内大型绿植。',
    lightRequirement: 'medium',
    waterRequirement: 'medium',
    temperatureRange: '15-28°C',
    colorSeed: 9,
    shapeType: 'tall'
  },
  {
    id: 'bird-of-paradise',
    name: '鹤望兰',
    scientificName: 'Strelitzia reginae',
    family: '鹤望兰科',
    genus: '鹤望兰属',
    description: '鹤望兰叶片宽大优美，花朵形似展翅欲飞的仙鹤，极具热带风情。',
    lightRequirement: 'strong',
    waterRequirement: 'medium',
    temperatureRange: '18-30°C',
    colorSeed: 10,
    shapeType: 'leafy'
  },
  {
    id: 'cactus',
    name: '仙人掌',
    scientificName: 'Cactaceae',
    family: '仙人掌科',
    genus: '仙人掌属',
    description: '仙人掌是典型的沙漠植物，茎肉质多汁，表面布满尖刺，极度耐旱。',
    lightRequirement: 'strong',
    waterRequirement: 'dry',
    temperatureRange: '10-35°C',
    colorSeed: 11,
    shapeType: 'cactus'
  },
  {
    id: 'boston-fern',
    name: '波士顿蕨',
    scientificName: 'Nephrolepis exaltata',
    family: '肾蕨科',
    genus: '肾蕨属',
    description: '波士顿蕨是最受欢迎的蕨类植物之一，叶片下垂优美，适合吊盆种植。',
    lightRequirement: 'medium',
    waterRequirement: 'wet',
    temperatureRange: '16-24°C',
    colorSeed: 12,
    shapeType: 'fern'
  },
  {
    id: 'zz-plant',
    name: '金钱树',
    scientificName: 'Zamioculcas zamiifolia',
    family: '天南星科',
    genus: '美铁芋属',
    description: '金钱树叶片圆润有光泽，排列整齐如串串铜钱，寓意招财进宝。',
    lightRequirement: 'weak',
    waterRequirement: 'dry',
    temperatureRange: '18-30°C',
    colorSeed: 13,
    shapeType: 'bushy'
  },
  {
    id: 'anthurium',
    name: '红掌',
    scientificName: 'Anthurium andraeanum',
    family: '天南星科',
    genus: '花烛属',
    description: '红掌佛焰苞鲜艳如蜡，常年开花不断，是喜庆吉祥的象征。',
    lightRequirement: 'medium',
    waterRequirement: 'wet',
    temperatureRange: '20-28°C',
    colorSeed: 14,
    shapeType: 'leafy'
  },
  {
    id: 'draceana',
    name: '巴西木',
    scientificName: 'Dracaena fragrans',
    family: '天门冬科',
    genus: '龙血树属',
    description: '巴西木株形优美规整，叶色翠绿有光泽，是著名的新一代室内观叶植物。',
    lightRequirement: 'medium',
    waterRequirement: 'medium',
    temperatureRange: '18-28°C',
    colorSeed: 15,
    shapeType: 'tall'
  },
  {
    id: 'ivy',
    name: '常春藤',
    scientificName: 'Hedera helix',
    family: '五加科',
    genus: '常春藤属',
    description: '常春藤是经典的攀援观叶植物，叶形优美，四季常青，可垂吊或攀附生长。',
    lightRequirement: 'medium',
    waterRequirement: 'medium',
    temperatureRange: '15-25°C',
    colorSeed: 16,
    shapeType: 'vine'
  },
  {
    id: 'aloe',
    name: '芦荟',
    scientificName: 'Aloe vera',
    family: '阿福花科',
    genus: '芦荟属',
    description: '芦荟叶片肥厚多汁，内含丰富凝胶，兼具美容、药用和观赏价值。',
    lightRequirement: 'strong',
    waterRequirement: 'dry',
    temperatureRange: '15-30°C',
    colorSeed: 17,
    shapeType: 'cactus'
  },
  {
    id: 'calathea',
    name: '竹芋',
    scientificName: 'Calathea',
    family: '竹芋科',
    genus: '竹芋属',
    description: '竹芋叶片斑纹绚丽多彩，有如艺术家精心绘制，是观叶植物中的珍品。',
    lightRequirement: 'weak',
    waterRequirement: 'wet',
    temperatureRange: '18-25°C',
    colorSeed: 18,
    shapeType: 'leafy'
  },
  {
    id: 'philo',
    name: '蔓绿绒',
    scientificName: 'Philodendron',
    family: '天南星科',
    genus: '喜林芋属',
    description: '蔓绿绒叶形多样，有裂叶、心形等多种形态，是热带雨林的代表性植物。',
    lightRequirement: 'weak',
    waterRequirement: 'medium',
    temperatureRange: '18-28°C',
    colorSeed: 19,
    shapeType: 'vine'
  },
  {
    id: 'aglaonema',
    name: '粗肋草',
    scientificName: 'Aglaonema',
    family: '天南星科',
    genus: '粗肋草属',
    description: '粗肋草叶片带有银白或粉红色斑纹，色彩丰富，耐阴性极强。',
    lightRequirement: 'weak',
    waterRequirement: 'medium',
    temperatureRange: '20-28°C',
    colorSeed: 20,
    shapeType: 'bushy'
  },
  {
    id: 'yucca',
    name: '丝兰',
    scientificName: 'Yucca',
    family: '天门冬科',
    genus: '丝兰属',
    description: '丝兰叶片坚硬呈剑形，株形挺拔有力，具有强烈的热带沙漠风情。',
    lightRequirement: 'strong',
    waterRequirement: 'dry',
    temperatureRange: '15-30°C',
    colorSeed: 21,
    shapeType: 'tall'
  },
  {
    id: 'begonia',
    name: '秋海棠',
    scientificName: 'Begonia',
    family: '秋海棠科',
    genus: '秋海棠属',
    description: '秋海棠叶片和花朵都极具观赏性，叶色斑斓，花期持久。',
    lightRequirement: 'medium',
    waterRequirement: 'wet',
    temperatureRange: '18-25°C',
    colorSeed: 22,
    shapeType: 'leafy'
  },
  {
    id: 'asparagus',
    name: '文竹',
    scientificName: 'Asparagus setaceus',
    family: '天门冬科',
    genus: '天门冬属',
    description: '文竹枝叶纤细如云，姿态优雅飘逸，是书房案头的经典植物。',
    lightRequirement: 'weak',
    waterRequirement: 'medium',
    temperatureRange: '15-25°C',
    colorSeed: 23,
    shapeType: 'fern'
  },
  {
    id: 'jade-plant',
    name: '玉树',
    scientificName: 'Crassula ovata',
    family: '景天科',
    genus: '青锁龙属',
    description: '玉树叶片肥厚如玉，枝干苍劲古朴，寓意吉祥富贵，易养护且长寿。',
    lightRequirement: 'strong',
    waterRequirement: 'dry',
    temperatureRange: '15-28°C',
    colorSeed: 24,
    shapeType: 'bushy'
  }
];
