import { Template, PAPER_SIZE } from '../types';

export const TEMPLATES: Template[] = [
  {
    id: 'crane',
    name: '纸鹤',
    nameEn: 'Crane',
    steps: [
      {
        id: 1,
        description: '将纸张对角对折，形成三角形',
        crease: {
          id: 'crane-1',
          start: { x: 0, y: 0 },
          end: { x: PAPER_SIZE, y: PAPER_SIZE },
          angle: Math.PI,
          type: 'valley',
          cornerIndex: 0,
        },
        duration: 1500,
      },
      {
        id: 2,
        description: '将三角形两个底角向顶点折叠',
        crease: {
          id: 'crane-2',
          start: { x: PAPER_SIZE / 2, y: 0 },
          end: { x: PAPER_SIZE / 2, y: PAPER_SIZE / 2 },
          angle: Math.PI * 0.6,
          type: 'valley',
          cornerIndex: 2,
        },
        duration: 1500,
      },
      {
        id: 3,
        description: '翻转纸张，将另一侧也向顶点折叠',
        crease: {
          id: 'crane-3',
          start: { x: PAPER_SIZE / 2, y: 0 },
          end: { x: PAPER_SIZE / 4, y: PAPER_SIZE / 2 },
          angle: Math.PI * 0.5,
          type: 'mountain',
          cornerIndex: 3,
        },
        duration: 1500,
      },
      {
        id: 4,
        description: '将下方尖角向上折叠，形成颈部',
        crease: {
          id: 'crane-4',
          start: { x: PAPER_SIZE / 2, y: PAPER_SIZE / 2 },
          end: { x: PAPER_SIZE / 2, y: PAPER_SIZE * 0.75 },
          angle: Math.PI * 0.7,
          type: 'valley',
          cornerIndex: 3,
        },
        duration: 1500,
      },
      {
        id: 5,
        description: '将顶部尖角向下折叠，形成鹤尾',
        crease: {
          id: 'crane-5',
          start: { x: PAPER_SIZE / 2, y: 0 },
          end: { x: PAPER_SIZE / 2, y: PAPER_SIZE / 4 },
          angle: Math.PI * 0.6,
          type: 'mountain',
          cornerIndex: 0,
        },
        duration: 1500,
      },
      {
        id: 6,
        description: '将颈部前端向下折叠形成头部',
        crease: {
          id: 'crane-6',
          start: { x: PAPER_SIZE * 0.4, y: PAPER_SIZE * 0.1 },
          end: { x: PAPER_SIZE * 0.6, y: PAPER_SIZE * 0.2 },
          angle: Math.PI * 0.8,
          type: 'valley',
          cornerIndex: 1,
        },
        duration: 1500,
      },
      {
        id: 7,
        description: '展开翅膀并整理形状',
        crease: {
          id: 'crane-7',
          start: { x: PAPER_SIZE * 0.25, y: PAPER_SIZE * 0.4 },
          end: { x: PAPER_SIZE * 0.75, y: PAPER_SIZE * 0.4 },
          angle: Math.PI * 0.4,
          type: 'mountain',
          cornerIndex: 2,
        },
        duration: 1500,
      },
      {
        id: 8,
        description: '纸鹤完成！',
        crease: {
          id: 'crane-8',
          start: { x: 0, y: 0 },
          end: { x: PAPER_SIZE, y: PAPER_SIZE },
          angle: Math.PI,
          type: 'valley',
          cornerIndex: 1,
        },
        duration: 1500,
      },
    ],
  },
  {
    id: 'boat',
    name: '纸船',
    nameEn: 'Boat',
    steps: [
      {
        id: 1,
        description: '将纸张向上对折',
        crease: {
          id: 'boat-1',
          start: { x: 0, y: PAPER_SIZE / 2 },
          end: { x: PAPER_SIZE, y: PAPER_SIZE / 2 },
          angle: Math.PI,
          type: 'valley',
          cornerIndex: 2,
        },
        duration: 1500,
      },
      {
        id: 2,
        description: '再次向上对折',
        crease: {
          id: 'boat-2',
          start: { x: 0, y: PAPER_SIZE / 4 },
          end: { x: PAPER_SIZE, y: PAPER_SIZE / 4 },
          angle: Math.PI,
          type: 'valley',
          cornerIndex: 3,
        },
        duration: 1500,
      },
      {
        id: 3,
        description: '将顶部两个角向中心折叠',
        crease: {
          id: 'boat-3',
          start: { x: PAPER_SIZE / 2, y: 0 },
          end: { x: PAPER_SIZE / 2, y: PAPER_SIZE / 2 },
          angle: Math.PI * 0.8,
          type: 'valley',
          cornerIndex: 0,
        },
        duration: 1500,
      },
      {
        id: 4,
        description: '将底部单层向上折叠',
        crease: {
          id: 'boat-4',
          start: { x: 0, y: PAPER_SIZE / 2 },
          end: { x: PAPER_SIZE, y: PAPER_SIZE / 2 },
          angle: Math.PI * 0.7,
          type: 'valley',
          cornerIndex: 2,
        },
        duration: 1500,
      },
      {
        id: 5,
        description: '翻转纸张，另一侧同样折叠',
        crease: {
          id: 'boat-5',
          start: { x: 0, y: PAPER_SIZE / 2 },
          end: { x: PAPER_SIZE, y: PAPER_SIZE / 2 },
          angle: Math.PI * 0.7,
          type: 'mountain',
          cornerIndex: 3,
        },
        duration: 1500,
      },
      {
        id: 6,
        description: '拉开底部两角并压平成菱形',
        crease: {
          id: 'boat-6',
          start: { x: PAPER_SIZE / 2, y: 0 },
          end: { x: PAPER_SIZE / 2, y: PAPER_SIZE },
          angle: Math.PI * 0.6,
          type: 'valley',
          cornerIndex: 1,
        },
        duration: 1500,
      },
      {
        id: 7,
        description: '拉起顶部三角形形成船身',
        crease: {
          id: 'boat-7',
          start: { x: PAPER_SIZE / 4, y: PAPER_SIZE / 2 },
          end: { x: PAPER_SIZE * 3 / 4, y: PAPER_SIZE / 2 },
          angle: Math.PI * 0.5,
          type: 'mountain',
          cornerIndex: 0,
        },
        duration: 1500,
      },
      {
        id: 8,
        description: '纸船完成！',
        crease: {
          id: 'boat-8',
          start: { x: 0, y: PAPER_SIZE / 2 },
          end: { x: PAPER_SIZE, y: PAPER_SIZE / 2 },
          angle: Math.PI,
          type: 'valley',
          cornerIndex: 2,
        },
        duration: 1500,
      },
    ],
  },
  {
    id: 'frog',
    name: '青蛙',
    nameEn: 'Frog',
    steps: [
      {
        id: 1,
        description: '将纸张水平对折后展开',
        crease: {
          id: 'frog-1',
          start: { x: 0, y: PAPER_SIZE / 2 },
          end: { x: PAPER_SIZE, y: PAPER_SIZE / 2 },
          angle: Math.PI,
          type: 'valley',
          cornerIndex: 2,
        },
        duration: 1500,
      },
      {
        id: 2,
        description: '将顶部两角向中心折叠形成三角形',
        crease: {
          id: 'frog-2',
          start: { x: PAPER_SIZE / 2, y: 0 },
          end: { x: PAPER_SIZE / 2, y: PAPER_SIZE / 2 },
          angle: Math.PI * 0.8,
          type: 'valley',
          cornerIndex: 0,
        },
        duration: 1500,
      },
      {
        id: 3,
        description: '将三角形底边两角向顶点折叠',
        crease: {
          id: 'frog-3',
          start: { x: PAPER_SIZE / 2, y: PAPER_SIZE / 2 },
          end: { x: PAPER_SIZE / 4, y: PAPER_SIZE / 4 },
          angle: Math.PI * 0.7,
          type: 'valley',
          cornerIndex: 3,
        },
        duration: 1500,
      },
      {
        id: 4,
        description: '将下半部分向上对折',
        crease: {
          id: 'frog-4',
          start: { x: 0, y: PAPER_SIZE * 0.75 },
          end: { x: PAPER_SIZE, y: PAPER_SIZE * 0.75 },
          angle: Math.PI * 0.9,
          type: 'valley',
          cornerIndex: 2,
        },
        duration: 1500,
      },
      {
        id: 5,
        description: '再次向上对折形成弹簧结构',
        crease: {
          id: 'frog-5',
          start: { x: 0, y: PAPER_SIZE * 0.6 },
          end: { x: PAPER_SIZE, y: PAPER_SIZE * 0.6 },
          angle: Math.PI * 0.8,
          type: 'mountain',
          cornerIndex: 3,
        },
        duration: 1500,
      },
      {
        id: 6,
        description: '将前部两角向外折叠形成前腿',
        crease: {
          id: 'frog-6',
          start: { x: PAPER_SIZE * 0.3, y: PAPER_SIZE * 0.4 },
          end: { x: PAPER_SIZE * 0.7, y: PAPER_SIZE * 0.4 },
          angle: Math.PI * 0.6,
          type: 'valley',
          cornerIndex: 1,
        },
        duration: 1500,
      },
      {
        id: 7,
        description: '整理后腿并按压弹簧',
        crease: {
          id: 'frog-7',
          start: { x: PAPER_SIZE * 0.2, y: PAPER_SIZE * 0.8 },
          end: { x: PAPER_SIZE * 0.8, y: PAPER_SIZE * 0.8 },
          angle: Math.PI * 0.5,
          type: 'mountain',
          cornerIndex: 2,
        },
        duration: 1500,
      },
      {
        id: 8,
        description: '青蛙完成！',
        crease: {
          id: 'frog-8',
          start: { x: 0, y: 0 },
          end: { x: PAPER_SIZE, y: PAPER_SIZE },
          angle: Math.PI,
          type: 'valley',
          cornerIndex: 1,
        },
        duration: 1500,
      },
    ],
  },
];
