export type EventCategory = '科技' | '人文' | '灾难' | '艺术';

export interface HistoryEvent {
  id: string;
  year: number;
  title: string;
  description: string;
  summary: string;
  category: EventCategory;
  influenceLevel: 1 | 2 | 3;
  icon: string;
}

export const events: HistoryEvent[] = [
  {
    id: '1',
    year: 1769,
    title: '瓦特改良蒸汽机',
    description: '詹姆斯·瓦特对纽科门蒸汽机进行了革命性改良，大大提高了能源效率，为工业革命提供了核心动力源。这项发明推动了工厂制度的建立，彻底改变了人类社会的生产方式。',
    summary: '开启工业革命时代的核心发明',
    category: '科技',
    influenceLevel: 3,
    icon: '⚙️',
  },
  {
    id: '2',
    year: 1825,
    title: '史蒂芬森蒸汽机车',
    description: '乔治·史蒂芬森设计的"旅行者号"蒸汽机车成功运行，标志着铁路时代的开始。第一条公共铁路斯托克顿-达灵顿铁路正式通车，开启了现代化陆路交通的新纪元。',
    summary: '铁路时代的开端',
    category: '科技',
    influenceLevel: 3,
    icon: '🚂',
  },
  {
    id: '3',
    year: 1831,
    title: '法拉第电磁感应',
    description: '迈克尔·法拉第发现电磁感应现象，为发电机和电动机的发明奠定了理论基础。这一发现直接推动了电力革命，使人类进入了电气时代。',
    summary: '电气时代的理论基石',
    category: '科技',
    influenceLevel: 3,
    icon: '⚡',
  },
  {
    id: '4',
    year: 1848,
    title: '《共产党宣言》发表',
    description: '卡尔·马克思和弗里德里希·恩格斯在伦敦发表《共产党宣言》，系统阐述了科学社会主义理论，对19世纪和20世纪的世界政治格局产生了深远影响。',
    summary: '社会主义运动的纲领性文献',
    category: '人文',
    influenceLevel: 3,
    icon: '📜',
  },
  {
    id: '5',
    year: 1859,
    title: '《物种起源》出版',
    description: '查尔斯·达尔文出版《物种起源》，提出进化论学说，挑战了传统的神创论观点，彻底改变了人类对生命起源和发展的认识。',
    summary: '进化论改变生物学世界观',
    category: '人文',
    influenceLevel: 3,
    icon: '📖',
  },
  {
    id: '6',
    year: 1876,
    title: '贝尔发明电话',
    description: '亚历山大·格拉汉姆·贝尔成功发明电话并获得专利，实现了人类历史上第一次远距离语音通信，开启了现代通讯时代。',
    summary: '现代通讯技术的诞生',
    category: '科技',
    influenceLevel: 2,
    icon: '📞',
  },
  {
    id: '7',
    year: 1879,
    title: '爱迪生发明电灯',
    description: '托马斯·爱迪生成功研制出实用的白炽灯泡，为人类带来了持续稳定的人工照明，彻底改变了人类的生活方式和作息规律。',
    summary: '照亮世界的发明',
    category: '科技',
    influenceLevel: 3,
    icon: '💡',
  },
  {
    id: '8',
    year: 1889,
    title: '埃菲尔铁塔落成',
    description: '为巴黎世界博览会建造的埃菲尔铁塔正式落成，高324米，成为当时世界最高建筑和现代建筑艺术的标志性作品。',
    summary: '工业时代的建筑杰作',
    category: '艺术',
    influenceLevel: 2,
    icon: '🗼',
  },
  {
    id: '9',
    year: 1903,
    title: '莱特兄弟首飞',
    description: '威尔伯·莱特和奥维尔·莱特在北卡罗来纳州成功完成人类历史上首次动力飞行，开启了人类征服天空的航空时代。',
    summary: '人类首次动力飞行成功',
    category: '科技',
    influenceLevel: 3,
    icon: '✈️',
  },
  {
    id: '10',
    year: 1905,
    title: '爱因斯坦相对论',
    description: '阿尔伯特·爱因斯坦发表狭义相对论，提出E=mc²质能公式，彻底颠覆了经典物理学的时空观，为核物理和宇宙学奠定了理论基础。',
    summary: '颠覆经典物理学时空观',
    category: '科技',
    influenceLevel: 3,
    icon: '🔬',
  },
  {
    id: '11',
    year: 1912,
    title: '泰坦尼克号沉没',
    description: '当时世界上最大最豪华的邮轮"泰坦尼克号"在处女航中撞上冰山沉没，造成1500多人遇难，是和平时期最严重的海难之一。',
    summary: '和平时期最惨重的海难',
    category: '灾难',
    influenceLevel: 2,
    icon: '🚢',
  },
  {
    id: '12',
    year: 1914,
    title: '第一次世界大战爆发',
    description: '奥匈帝国向塞尔维亚宣战，第一次世界大战正式爆发。这场持续四年的战争造成约1600万人死亡，彻底改变了世界政治格局。',
    summary: '人类历史上首次全球规模战争',
    category: '灾难',
    influenceLevel: 3,
    icon: '⚔️',
  },
  {
    id: '13',
    year: 1918,
    title: '西班牙流感大流行',
    description: 'H1N1甲型流感病毒引发全球大流行，感染人数约5亿，造成约2000-5000万人死亡，是人类历史上最致命的传染病之一。',
    summary: '人类历史上最致命的大流感',
    category: '灾难',
    influenceLevel: 3,
    icon: '🦠',
  },
  {
    id: '14',
    year: 1922,
    title: '《尤利西斯》出版',
    description: '詹姆斯·乔伊斯的意识流小说《尤利西斯》在巴黎出版，以其创新的叙事手法和对人类内心世界的深刻探索，成为20世纪文学的里程碑。',
    summary: '意识流文学的巅峰之作',
    category: '艺术',
    influenceLevel: 2,
    icon: '📚',
  },
  {
    id: '15',
    year: 1939,
    title: '第二次世界大战爆发',
    description: '德国入侵波兰，第二次世界大战全面爆发。这场持续六年的战争造成约7000万人死亡，是人类历史上规模最大、伤亡最惨重的战争。',
    summary: '人类历史上规模最大的战争',
    category: '灾难',
    influenceLevel: 3,
    icon: '💥',
  },
  {
    id: '16',
    year: 1945,
    title: '原子弹爆炸',
    description: '美国在日本广岛和长崎投下原子弹，造成约20万人死亡。这是人类历史上首次也是唯一一次在战争中使用核武器，标志着核时代的开始。',
    summary: '核时代的开始',
    category: '灾难',
    influenceLevel: 3,
    icon: '☢️',
  },
  {
    id: '17',
    year: 1945,
    title: '联合国成立',
    description: '《联合国宪章》正式生效，联合国宣告成立。这一国际组织致力于维护世界和平与安全，促进国际合作，是二战后国际秩序的核心支柱。',
    summary: '战后国际秩序的核心支柱',
    category: '人文',
    influenceLevel: 3,
    icon: '🌍',
  },
  {
    id: '18',
    year: 1957,
    title: '斯普特尼克1号发射',
    description: '苏联成功发射人类第一颗人造地球卫星"斯普特尼克1号"，开启了人类探索太空的新纪元，引发了美苏太空竞赛。',
    summary: '人类太空时代的开端',
    category: '科技',
    influenceLevel: 3,
    icon: '🛰️',
  },
  {
    id: '19',
    year: 1963,
    title: '肯尼迪遇刺',
    description: '美国总统约翰·F·肯尼迪在达拉斯遇刺身亡，这一事件震惊世界，对美国政治和社会产生了深远影响，至今仍有诸多谜团。',
    summary: '震惊世界的政治暗杀',
    category: '人文',
    influenceLevel: 2,
    icon: '🎯',
  },
  {
    id: '20',
    year: 1968,
    title: '《2001太空漫游》上映',
    description: '斯坦利·库布里克导演的科幻史诗电影《2001太空漫游》上映，以其革命性的视觉特效和深刻的哲学思考，重新定义了科幻电影的艺术高度。',
    summary: '科幻电影史上的里程碑',
    category: '艺术',
    influenceLevel: 3,
    icon: '🎬',
  },
  {
    id: '21',
    year: 1969,
    title: '阿波罗11号登月',
    description: '美国宇航员尼尔·阿姆斯特朗和巴兹·奥尔德林成功登上月球，阿姆斯特朗成为第一个踏上月球的人类，实现了"个人的一小步，人类的一大步"。',
    summary: '人类首次登月成功',
    category: '科技',
    influenceLevel: 3,
    icon: '🌙',
  },
  {
    id: '22',
    year: 1976,
    title: '文化大革命结束',
    description: '中国"四人帮"被粉碎，持续十年的"文化大革命"正式结束。这一事件标志着中国进入了新的历史时期，为后来的改革开放奠定了基础。',
    summary: '中国当代史的转折点',
    category: '人文',
    influenceLevel: 3,
    icon: '🏛️',
  },
  {
    id: '23',
    year: 1978,
    title: '改革开放',
    description: '中国共产党十一届三中全会召开，确立了改革开放的基本国策，开启了中国特色社会主义道路，创造了人类经济发展史上的奇迹。',
    summary: '中国经济腾飞的起点',
    category: '人文',
    influenceLevel: 3,
    icon: '🚀',
  },
  {
    id: '24',
    year: 1985,
    title: '互联网诞生',
    description: 'TCP/IP协议成为网络标准，ARPANET正式转变为互联网。这项发明彻底改变了人类的信息传播方式，开启了信息时代。',
    summary: '信息时代的开端',
    category: '科技',
    influenceLevel: 3,
    icon: '🌐',
  },
  {
    id: '25',
    year: 1989,
    title: '柏林墙倒塌',
    description: '分割东西德28年的柏林墙被推倒，象征着冷战的结束和德国的统一。这一事件标志着雅尔塔体系的瓦解，世界格局发生重大变化。',
    summary: '冷战结束的象征',
    category: '人文',
    influenceLevel: 3,
    icon: '🧱',
  },
  {
    id: '26',
    year: 1991,
    title: '苏联解体',
    description: '苏维埃社会主义共和国联盟正式解体，分裂为15个独立国家。这一事件标志着冷战的正式结束和两极格局的终结。',
    summary: '两极格局终结',
    category: '人文',
    influenceLevel: 3,
    icon: '🔔',
  },
  {
    id: '27',
    year: 1995,
    title: '万维网普及',
    description: '蒂姆·伯纳斯-李发明的万维网（WWW）开始向公众开放，HTML和HTTP协议成为标准，互联网开始从学术圈走向大众。',
    summary: 'WWW开启互联网大众化',
    category: '科技',
    influenceLevel: 3,
    icon: '💻',
  },
  {
    id: '28',
    year: 2001,
    title: '911恐怖袭击',
    description: '基地组织对美国纽约和华盛顿发动恐怖袭击，造成约3000人死亡，直接导致了美国的反恐战争和全球安全格局的重大变化。',
    summary: '改变21世纪世界格局的事件',
    category: '灾难',
    influenceLevel: 3,
    icon: '🏙️',
  },
  {
    id: '29',
    year: 2003,
    title: '人类基因组计划完成',
    description: '国际人类基因组计划宣布完成人类基因组测序草图，首次完整绘制出人类DNA图谱，为医学和生物学研究开辟了新纪元。',
    summary: '破解人类生命密码',
    category: '科技',
    influenceLevel: 3,
    icon: '🧬',
  },
  {
    id: '30',
    year: 2004,
    title: '印度洋大海啸',
    description: '印度洋发生9.3级地震并引发巨大海啸，造成约23万人死亡，是人类历史上最严重的自然灾害之一。',
    summary: '人类历史上最严重的海啸灾难',
    category: '灾难',
    influenceLevel: 3,
    icon: '🌊',
  },
  {
    id: '31',
    year: 2007,
    title: 'iPhone发布',
    description: '史蒂夫·乔布斯在Macworld大会上发布第一代iPhone，重新定义了智能手机，开启了移动互联网时代，彻底改变了人类的生活方式。',
    summary: '移动互联网时代的开端',
    category: '科技',
    influenceLevel: 3,
    icon: '📱',
  },
  {
    id: '32',
    year: 2008,
    title: '北京奥运会',
    description: '第29届夏季奥林匹克运动会在北京举行，这是中国首次举办奥运会，开幕式的壮观表演震惊世界，中国以51枚金牌位居榜首。',
    summary: '中国首次举办奥运会',
    category: '艺术',
    influenceLevel: 3,
    icon: '🏅',
  },
  {
    id: '33',
    year: 2008,
    title: '全球金融危机',
    description: '美国次贷危机引发全球金融海啸，雷曼兄弟破产，全球经济陷入大萧条以来最严重的衰退，影响持续多年。',
    summary: '大萧条以来最严重的金融危机',
    category: '灾难',
    influenceLevel: 3,
    icon: '📉',
  },
  {
    id: '34',
    year: 2012,
    title: '希格斯玻色子发现',
    description: '欧洲核子研究中心宣布发现希格斯玻色子（"上帝粒子"），证实了标准模型的预测，是粒子物理学的重大突破。',
    summary: '粒子物理学的重大突破',
    category: '科技',
    influenceLevel: 2,
    icon: '⚛️',
  },
  {
    id: '35',
    year: 2015,
    title: '《巴黎协定》签署',
    description: '196个国家在巴黎签署《巴黎协定》，承诺将全球气温升幅控制在2摄氏度以内，是人类应对气候变化的里程碑。',
    summary: '全球气候治理的里程碑',
    category: '人文',
    influenceLevel: 3,
    icon: '🌱',
  },
  {
    id: '36',
    year: 2019,
    title: '新冠疫情爆发',
    description: '新型冠状病毒（COVID-19）在武汉被发现并迅速蔓延全球，世界卫生组织宣布其为全球大流行，对全球公共卫生和经济造成深远影响。',
    summary: '百年一遇的全球大流行',
    category: '灾难',
    influenceLevel: 3,
    icon: '😷',
  },
  {
    id: '37',
    year: 2020,
    title: 'SpaceX载人航天',
    description: 'SpaceX公司的龙飞船成功将两名宇航员送入国际空间站，实现了人类历史上首次商业载人航天任务，开启了商业太空时代。',
    summary: '商业太空时代的开端',
    category: '科技',
    influenceLevel: 2,
    icon: '🚀',
  },
  {
    id: '38',
    year: 2022,
    title: 'AI绘画技术突破',
    description: 'Stable Diffusion等AI绘画模型开源发布，人工智能生成内容（AIGC）技术取得重大突破，引发艺术创作领域的革命。',
    summary: 'AI艺术创作的革命',
    category: '艺术',
    influenceLevel: 3,
    icon: '🎨',
  },
  {
    id: '39',
    year: 2022,
    title: 'ChatGPT发布',
    description: 'OpenAI发布ChatGPT大语言模型，人工智能技术取得突破性进展，引发全球AI技术竞赛，开启了通用人工智能时代的序幕。',
    summary: '通用人工智能时代的序幕',
    category: '科技',
    influenceLevel: 3,
    icon: '🤖',
  },
];

export const categoryColors: Record<EventCategory, string> = {
  科技: '#4dabf7',
  人文: '#ff922b',
  灾难: '#fa5252',
  艺术: '#cc5de8',
};

export const dotSizes: Record<1 | 2 | 3, number> = {
  1: 8,
  2: 10,
  3: 12,
};
