export interface PoemLine {
  text: string;
  author: string;
  dynasty: string;
  title: string;
}

export interface CoupletPair {
  upper: string;
  lower: string;
}

const POEMS: PoemLine[] = [
  { text: "床前明月光，疑是地上霜", author: "李白", dynasty: "唐", title: "静夜思" },
  { text: "举头望明月，低头思故乡", author: "李白", dynasty: "唐", title: "静夜思" },
  { text: "春风又绿江南岸，明月何时照我还", author: "王安石", dynasty: "宋", title: "泊船瓜洲" },
  { text: "大漠孤烟直，长河落日圆", author: "王维", dynasty: "唐", title: "使至塞上" },
  { text: "白日依山尽，黄河入海流", author: "王之涣", dynasty: "唐", title: "登鹳雀楼" },
  { text: "欲穷千里目，更上一层楼", author: "王之涣", dynasty: "唐", title: "登鹳雀楼" },
  { text: "两个黄鹂鸣翠柳，一行白鹭上青天", author: "杜甫", dynasty: "唐", title: "绝句" },
  { text: "窗含西岭千秋雪，门泊东吴万里船", author: "杜甫", dynasty: "唐", title: "绝句" },
  { text: "千山鸟飞绝，万径人踪灭", author: "柳宗元", dynasty: "唐", title: "江雪" },
  { text: "孤舟蓑笠翁，独钓寒江雪", author: "柳宗元", dynasty: "唐", title: "江雪" },
  { text: "春眠不觉晓，处处闻啼鸟", author: "孟浩然", dynasty: "唐", title: "春晓" },
  { text: "夜来风雨声，花落知多少", author: "孟浩然", dynasty: "唐", title: "春晓" },
  { text: "锄禾日当午，汗滴禾下土", author: "李绅", dynasty: "唐", title: "悯农" },
  { text: "谁知盘中餐，粒粒皆辛苦", author: "李绅", dynasty: "唐", title: "悯农" },
  { text: "离离原上草，一岁一枯荣", author: "白居易", dynasty: "唐", title: "赋得古原草送别" },
  { text: "野火烧不尽，春风吹又生", author: "白居易", dynasty: "唐", title: "赋得古原草送别" },
  { text: "日照香炉生紫烟，遥看瀑布挂前川", author: "李白", dynasty: "唐", title: "望庐山瀑布" },
  { text: "飞流直下三千尺，疑是银河落九天", author: "李白", dynasty: "唐", title: "望庐山瀑布" },
  { text: "朝辞白帝彩云间，千里江陵一日还", author: "李白", dynasty: "唐", title: "早发白帝城" },
  { text: "两岸猿声啼不住，轻舟已过万重山", author: "李白", dynasty: "唐", title: "早发白帝城" },
  { text: "故人西辞黄鹤楼，烟花三月下扬州", author: "李白", dynasty: "唐", title: "黄鹤楼送孟浩然之广陵" },
  { text: "孤帆远影碧空尽，唯见长江天际流", author: "李白", dynasty: "唐", title: "黄鹤楼送孟浩然之广陵" },
  { text: "月落乌啼霜满天，江枫渔火对愁眠", author: "张继", dynasty: "唐", title: "枫桥夜泊" },
  { text: "姑苏城外寒山寺，夜半钟声到客船", author: "张继", dynasty: "唐", title: "枫桥夜泊" },
  { text: "空山新雨后，天气晚来秋", author: "王维", dynasty: "唐", title: "山居秋暝" },
  { text: "明月松间照，清泉石上流", author: "王维", dynasty: "唐", title: "山居秋暝" },
  { text: "红豆生南国，春来发几枝", author: "王维", dynasty: "唐", title: "相思" },
  { text: "愿君多采撷，此物最相思", author: "王维", dynasty: "唐", title: "相思" },
  { text: "独在异乡为异客，每逢佳节倍思亲", author: "王维", dynasty: "唐", title: "九月九日忆山东兄弟" },
  { text: "遥知兄弟登高处，遍插茱萸少一人", author: "王维", dynasty: "唐", title: "九月九日忆山东兄弟" },
  { text: "葡萄美酒夜光杯，欲饮琵琶马上催", author: "王翰", dynasty: "唐", title: "凉州词" },
  { text: "醉卧沙场君莫笑，古来征战几人回", author: "王翰", dynasty: "唐", title: "凉州词" },
  { text: "秦时明月汉时关，万里长征人未还", author: "王昌龄", dynasty: "唐", title: "出塞" },
  { text: "但使龙城飞将在，不教胡马度阴山", author: "王昌龄", dynasty: "唐", title: "出塞" },
  { text: "寒雨连江夜入吴，平明送客楚山孤", author: "王昌龄", dynasty: "唐", title: "芙蓉楼送辛渐" },
  { text: "洛阳亲友如相问，一片冰心在玉壶", author: "王昌龄", dynasty: "唐", title: "芙蓉楼送辛渐" },
  { text: "千里莺啼绿映红，水村山郭酒旗风", author: "杜牧", dynasty: "唐", title: "江南春" },
  { text: "南朝四百八十寺，多少楼台烟雨中", author: "杜牧", dynasty: "唐", title: "江南春" },
  { text: "远上寒山石径斜，白云生处有人家", author: "杜牧", dynasty: "唐", title: "山行" },
  { text: "停车坐爱枫林晚，霜叶红于二月花", author: "杜牧", dynasty: "唐", title: "山行" },
  { text: "清明时节雨纷纷，路上行人欲断魂", author: "杜牧", dynasty: "唐", title: "清明" },
  { text: "借问酒家何处有，牧童遥指杏花村", author: "杜牧", dynasty: "唐", title: "清明" },
  { text: "君问归期未有期，巴山夜雨涨秋池", author: "李商隐", dynasty: "唐", title: "夜雨寄北" },
  { text: "何当共剪西窗烛，却话巴山夜雨时", author: "李商隐", dynasty: "唐", title: "夜雨寄北" },
  { text: "相见时难别亦难，东风无力百花残", author: "李商隐", dynasty: "唐", title: "无题" },
  { text: "春蚕到死丝方尽，蜡炬成灰泪始干", author: "李商隐", dynasty: "唐", title: "无题" },
  { text: "海内存知己，天涯若比邻", author: "王勃", dynasty: "唐", title: "送杜少府之任蜀州" },
  { text: "无边落木萧萧下，不尽长江滚滚来", author: "杜甫", dynasty: "唐", title: "登高" },
  { text: "感时花溅泪，恨别鸟惊心", author: "杜甫", dynasty: "唐", title: "春望" },
  { text: "烽火连三月，家书抵万金", author: "杜甫", dynasty: "唐", title: "春望" },
  { text: "随风潜入夜，润物细无声", author: "杜甫", dynasty: "唐", title: "春夜喜雨" },
  { text: "会当凌绝顶，一览众山小", author: "杜甫", dynasty: "唐", title: "望岳" },
  { text: "安得广厦千万间，大庇天下寒士俱欢颜", author: "杜甫", dynasty: "唐", title: "茅屋为秋风所破歌" },
  { text: "天生我材必有用，千金散尽还复来", author: "李白", dynasty: "唐", title: "将进酒" },
  { text: "人生得意须尽欢，莫使金樽空对月", author: "李白", dynasty: "唐", title: "将进酒" },
  { text: "长风破浪会有时，直挂云帆济沧海", author: "李白", dynasty: "唐", title: "行路难" },
  { text: "安能摧眉折腰事权贵，使我不得开心颜", author: "李白", dynasty: "唐", title: "梦游天姥吟留别" },
  { text: "君不见黄河之水天上来，奔流到海不复回", author: "李白", dynasty: "唐", title: "将进酒" },
  { text: "抽刀断水水更流，举杯消愁愁更愁", author: "李白", dynasty: "唐", title: "宣州谢朓楼饯别校书叔云" },
  { text: "问君能有几多愁，恰似一江春水向东流", author: "李煜", dynasty: "五代", title: "虞美人" },
  { text: "春花秋月何时了，往事知多少", author: "李煜", dynasty: "五代", title: "虞美人" },
  { text: "无可奈何花落去，似曾相识燕归来", author: "晏殊", dynasty: "宋", title: "浣溪沙" },
  { text: "明月几时有，把酒问青天", author: "苏轼", dynasty: "宋", title: "水调歌头" },
  { text: "但愿人长久，千里共婵娟", author: "苏轼", dynasty: "宋", title: "水调歌头" },
  { text: "大江东去，浪淘尽，千古风流人物", author: "苏轼", dynasty: "宋", title: "念奴娇·赤壁怀古" },
  { text: "人生如梦，一尊还酹江月", author: "苏轼", dynasty: "宋", title: "念奴娇·赤壁怀古" },
  { text: "十年生死两茫茫，不思量，自难忘", author: "苏轼", dynasty: "宋", title: "江城子" },
  { text: "相顾无言，惟有泪千行", author: "苏轼", dynasty: "宋", title: "江城子" },
  { text: "寻寻觅觅，冷冷清清，凄凄惨惨戚戚", author: "李清照", dynasty: "宋", title: "声声慢" },
  { text: "这次第，怎一个愁字了得", author: "李清照", dynasty: "宋", title: "声声慢" },
  { text: "知否，知否，应是绿肥红瘦", author: "李清照", dynasty: "宋", title: "如梦令" },
  { text: "莫道不销魂，帘卷西风，人比黄花瘦", author: "李清照", dynasty: "宋", title: "醉花阴" },
  { text: "生当作人杰，死亦为鬼雄", author: "李清照", dynasty: "宋", title: "夏日绝句" },
  { text: "山重水复疑无路，柳暗花明又一村", author: "陆游", dynasty: "宋", title: "游山西村" },
  { text: "纸上得来终觉浅，绝知此事要躬行", author: "陆游", dynasty: "宋", title: "冬夜读书示子聿" },
  { text: "王师北定中原日，家祭无忘告乃翁", author: "陆游", dynasty: "宋", title: "示儿" },
  { text: "小楼一夜听春雨，深巷明朝卖杏花", author: "陆游", dynasty: "宋", title: "临安春雨初霁" },
  { text: "位卑未敢忘忧国，事定犹须待阖棺", author: "陆游", dynasty: "宋", title: "病起书怀" },
  { text: "出师未捷身先死，长使英雄泪满襟", author: "杜甫", dynasty: "唐", title: "蜀相" },
  { text: "接天莲叶无穷碧，映日荷花别样红", author: "杨万里", dynasty: "宋", title: "晓出净慈寺送林子方" },
  { text: "小荷才露尖尖角，早有蜻蜓立上头", author: "杨万里", dynasty: "宋", title: "小池" },
  { text: "春风得意马蹄疾，一日看尽长安花", author: "孟郊", dynasty: "唐", title: "登科后" },
  { text: "谁言寸草心，报得三春晖", author: "孟郊", dynasty: "唐", title: "游子吟" },
  { text: "慈母手中线，游子身上衣", author: "孟郊", dynasty: "唐", title: "游子吟" },
  { text: "黑发不知勤学早，白首方悔读书迟", author: "颜真卿", dynasty: "唐", title: "劝学" },
  { text: "少壮不努力，老大徒伤悲", author: "汉乐府", dynasty: "汉", title: "长歌行" },
  { text: "老骥伏枥，志在千里", author: "曹操", dynasty: "汉", title: "龟虽寿" },
  { text: "烈士暮年，壮心不已", author: "曹操", dynasty: "汉", title: "龟虽寿" },
  { text: "对酒当歌，人生几何", author: "曹操", dynasty: "汉", title: "短歌行" },
  { text: "青青子衿，悠悠我心", author: "曹操", dynasty: "汉", title: "短歌行" },
  { text: "山不在高，有仙则名", author: "刘禹锡", dynasty: "唐", title: "陋室铭" },
  { text: "水不在深，有龙则灵", author: "刘禹锡", dynasty: "唐", title: "陋室铭" },
  { text: "沉舟侧畔千帆过，病树前头万木春", author: "刘禹锡", dynasty: "唐", title: "酬乐天扬州初逢席上见赠" },
  { text: "旧时王谢堂前燕，飞入寻常百姓家", author: "刘禹锡", dynasty: "唐", title: "乌衣巷" },
  { text: "东边日出西边雨，道是无晴却有晴", author: "刘禹锡", dynasty: "唐", title: "竹枝词" },
  { text: "落霞与孤鹜齐飞，秋水共长天一色", author: "王勃", dynasty: "唐", title: "滕王阁序" },
  { text: "醉翁之意不在酒，在乎山水之间也", author: "欧阳修", dynasty: "宋", title: "醉翁亭记" },
  { text: "先天下之忧而忧，后天下之乐而乐", author: "范仲淹", dynasty: "宋", title: "岳阳楼记" },
  { text: "不以物喜，不以己悲", author: "范仲淹", dynasty: "宋", title: "岳阳楼记" },
  { text: "出淤泥而不染，濯清涟而不妖", author: "周敦颐", dynasty: "宋", title: "爱莲说" },
  { text: "予独爱莲之出淤泥而不染", author: "周敦颐", dynasty: "宋", title: "爱莲说" },
  { text: "等闲识得东风面，万紫千红总是春", author: "朱熹", dynasty: "宋", title: "春日" },
  { text: "问渠那得清如许，为有源头活水来", author: "朱熹", dynasty: "宋", title: "观书有感" },
  { text: "衣带渐宽终不悔，为伊消得人憔悴", author: "柳永", dynasty: "宋", title: "蝶恋花" },
  { text: "多情自古伤离别，更那堪冷落清秋节", author: "柳永", dynasty: "宋", title: "雨霖铃" },
  { text: "今宵酒醒何处，杨柳岸晓风残月", author: "柳永", dynasty: "宋", title: "雨霖铃" },
  { text: "众里寻他千百度，蓦然回首，那人却在灯火阑珊处", author: "辛弃疾", dynasty: "宋", title: "青玉案" },
  { text: "醉里挑灯看剑，梦回吹角连营", author: "辛弃疾", dynasty: "宋", title: "破阵子" },
  { text: "了却君王天下事，赢得生前身后名", author: "辛弃疾", dynasty: "宋", title: "破阵子" },
  { text: "凭谁问，廉颇老矣，尚能饭否", author: "辛弃疾", dynasty: "宋", title: "永遇乐" },
  { text: "千古江山，英雄无觅孙仲谋处", author: "辛弃疾", dynasty: "宋", title: "永遇乐" },
  { text: "青山遮不住，毕竟东流去", author: "辛弃疾", dynasty: "宋", title: "菩萨蛮" },
  { text: "稻花香里说丰年，听取蛙声一片", author: "辛弃疾", dynasty: "宋", title: "西江月" },
  { text: "七八个星天外，两三点雨山前", author: "辛弃疾", dynasty: "宋", title: "西江月" }
];

const COUPLETS: CoupletPair[] = [
  { upper: "春风又绿江南岸", lower: "秋月重明蓟北关" },
  { upper: "明月松间照", lower: "清泉石上流" },
  { upper: "两个黄鹂鸣翠柳", lower: "一行白鹭上青天" },
  { upper: "窗含西岭千秋雪", lower: "门泊东吴万里船" },
  { upper: "千山鸟飞绝", lower: "万径人踪灭" },
  { upper: "白日依山尽", lower: "黄河入海流" },
  { upper: "欲穷千里目", lower: "更上一层楼" },
  { upper: "大漠孤烟直", lower: "长河落日圆" },
  { upper: "野火烧不尽", lower: "春风吹又生" },
  { upper: "飞流直下三千尺", lower: "疑是银河落九天" },
  { upper: "两岸猿声啼不住", lower: "轻舟已过万重山" },
  { upper: "孤帆远影碧空尽", lower: "唯见长江天际流" },
  { upper: "月落乌啼霜满天", lower: "江枫渔火对愁眠" },
  { upper: "姑苏城外寒山寺", lower: "夜半钟声到客船" },
  { upper: "空山新雨后", lower: "天气晚来秋" },
  { upper: "独在异乡为异客", lower: "每逢佳节倍思亲" },
  { upper: "遥知兄弟登高处", lower: "遍插茱萸少一人" },
  { upper: "葡萄美酒夜光杯", lower: "欲饮琵琶马上催" },
  { upper: "醉卧沙场君莫笑", lower: "古来征战几人回" },
  { upper: "秦时明月汉时关", lower: "万里长征人未还" },
  { upper: "但使龙城飞将在", lower: "不教胡马度阴山" },
  { upper: "寒雨连江夜入吴", lower: "平明送客楚山孤" },
  { upper: "洛阳亲友如相问", lower: "一片冰心在玉壶" },
  { upper: "千里莺啼绿映红", lower: "水村山郭酒旗风" },
  { upper: "南朝四百八十寺", lower: "多少楼台烟雨中" },
  { upper: "远上寒山石径斜", lower: "白云生处有人家" },
  { upper: "停车坐爱枫林晚", lower: "霜叶红于二月花" },
  { upper: "清明时节雨纷纷", lower: "路上行人欲断魂" },
  { upper: "借问酒家何处有", lower: "牧童遥指杏花村" },
  { upper: "君问归期未有期", lower: "巴山夜雨涨秋池" },
  { upper: "何当共剪西窗烛", lower: "却话巴山夜雨时" },
  { upper: "相见时难别亦难", lower: "东风无力百花残" },
  { upper: "春蚕到死丝方尽", lower: "蜡炬成灰泪始干" },
  { upper: "海内存知己", lower: "天涯若比邻" },
  { upper: "无边落木萧萧下", lower: "不尽长江滚滚来" },
  { upper: "感时花溅泪", lower: "恨别鸟惊心" },
  { upper: "烽火连三月", lower: "家书抵万金" },
  { upper: "随风潜入夜", lower: "润物细无声" },
  { upper: "会当凌绝顶", lower: "一览众山小" },
  { upper: "天生我材必有用", lower: "千金散尽还复来" },
  { upper: "人生得意须尽欢", lower: "莫使金樽空对月" },
  { upper: "长风破浪会有时", lower: "直挂云帆济沧海" },
  { upper: "抽刀断水水更流", lower: "举杯消愁愁更愁" },
  { upper: "问君能有几多愁", lower: "恰似一江春水向东流" },
  { upper: "无可奈何花落去", lower: "似曾相识燕归来" },
  { upper: "但愿人长久", lower: "千里共婵娟" },
  { upper: "大江东去浪淘尽", lower: "千古风流人物" },
  { upper: "寻寻觅觅冷冷清清", lower: "凄凄惨惨戚戚" },
  { upper: "莫道不销魂", lower: "人比黄花瘦" },
  { upper: "生当作人杰", lower: "死亦为鬼雄" },
  { upper: "山重水复疑无路", lower: "柳暗花明又一村" },
  { upper: "纸上得来终觉浅", lower: "绝知此事要躬行" },
  { upper: "小楼一夜听春雨", lower: "深巷明朝卖杏花" },
  { upper: "位卑未敢忘忧国", lower: "事定犹须待阖棺" },
  { upper: "出师未捷身先死", lower: "长使英雄泪满襟" },
  { upper: "接天莲叶无穷碧", lower: "映日荷花别样红" },
  { upper: "小荷才露尖尖角", lower: "早有蜻蜓立上头" },
  { upper: "春风得意马蹄疾", lower: "一日看尽长安花" },
  { upper: "谁言寸草心", lower: "报得三春晖" },
  { upper: "慈母手中线", lower: "游子身上衣" },
  { upper: "黑发不知勤学早", lower: "白首方悔读书迟" },
  { upper: "少壮不努力", lower: "老大徒伤悲" },
  { upper: "老骥伏枥", lower: "志在千里" },
  { upper: "烈士暮年", lower: "壮心不已" },
  { upper: "对酒当歌", lower: "人生几何" },
  { upper: "青青子衿", lower: "悠悠我心" },
  { upper: "山不在高", lower: "有仙则名" },
  { upper: "水不在深", lower: "有龙则灵" },
  { upper: "沉舟侧畔千帆过", lower: "病树前头万木春" },
  { upper: "旧时王谢堂前燕", lower: "飞入寻常百姓家" },
  { upper: "东边日出西边雨", lower: "道是无晴却有晴" },
  { upper: "落霞与孤鹜齐飞", lower: "秋水共长天一色" },
  { upper: "醉翁之意不在酒", lower: "在乎山水之间也" },
  { upper: "先天下之忧而忧", lower: "后天下之乐而乐" },
  { upper: "不以物喜", lower: "不以己悲" },
  { upper: "出淤泥而不染", lower: "濯清涟而不妖" },
  { upper: "等闲识得东风面", lower: "万紫千红总是春" },
  { upper: "问渠那得清如许", lower: "为有源头活水来" },
  { upper: "衣带渐宽终不悔", lower: "为伊消得人憔悴" },
  { upper: "多情自古伤离别", lower: "更那堪冷落清秋节" },
  { upper: "今宵酒醒何处", lower: "杨柳岸晓风残月" },
  { upper: "众里寻他千百度", lower: "那人却在灯火阑珊处" },
  { upper: "醉里挑灯看剑", lower: "梦回吹角连营" },
  { upper: "了却君王天下事", lower: "赢得生前身后名" },
  { upper: "青山遮不住", lower: "毕竟东流去" },
  { upper: "稻花香里说丰年", lower: "听取蛙声一片" },
  { upper: "七八个星天外", lower: "两三点雨山前" },
  { upper: "桃李春风一杯酒", lower: "江湖夜雨十年灯" },
  { upper: "三顾频烦天下计", lower: "两朝开济老臣心" },
  { upper: "映阶碧草自春色", lower: "隔叶黄鹂空好音" },
  { upper: "五更鼓角声悲壮", lower: "三峡星河影动摇" },
  { upper: "一去紫台连朔漠", lower: "独留青冢向黄昏" },
  { upper: "画图省识春风面", lower: "环佩空归月夜魂" },
  { upper: "风急天高猿啸哀", lower: "渚清沙白鸟飞回" },
  { upper: "万里悲秋常作客", lower: "百年多病独登台" },
  { upper: "艰难苦恨繁霜鬓", lower: "潦倒新停浊酒杯" },
  { upper: "身无彩凤双飞翼", lower: "心有灵犀一点通" },
  { upper: "隔座送钩春酒暖", lower: "分曹射覆蜡灯红" },
  { upper: "庄生晓梦迷蝴蝶", lower: "望帝春心托杜鹃" },
  { upper: "沧海月明珠有泪", lower: "蓝田日暖玉生烟" },
  { upper: "此情可待成追忆", lower: "只是当时已惘然" },
  { upper: "岁岁金河复玉关", lower: "朝朝马策与刀环" },
  { upper: "三春白雪归青冢", lower: "万里黄河绕黑山" },
  { upper: "回乐峰前沙似雪", lower: "受降城外月如霜" },
  { upper: "不知何处吹芦管", lower: "一夜征人尽望乡" }
];

export function searchPoems(keyword: string): PoemLine[] {
  if (!keyword.trim()) return [];
  const kw = keyword.trim();
  const results: PoemLine[] = [];
  for (let i = 0; i < POEMS.length; i++) {
    if (POEMS[i].text.includes(kw)) {
      results.push(POEMS[i]);
    }
  }
  return results;
}

export function getRandomCouplet(): CoupletPair {
  const idx = Math.floor(Math.random() * COUPLETS.length);
  return COUPLETS[idx];
}

export function getAllPoems(): PoemLine[] {
  return POEMS.slice();
}

export function getAllCouplets(): CoupletPair[] {
  return COUPLETS.slice();
}
